export const DEFAULT_COLORS = {
  PRIMARY: 0x5865F2,
  SUCCESS: 0x57F287,
  WARNING: 0xFEE75C,
  DANGER: 0xED4245,
  INFO: 0x3498DB,
  SECONDARY: 0x2B2D31,
  GOLD: 0xF1C40F,
  PURPLE: 0x9B59B6,
} as const;

export const EMOJIS = {
  COIN: '🪙',
  XP: '✨',
  LEVEL: '⭐',
  STREAK: '🔥',
  RANK: '🏆',
  VOICE: '🎤',
  MESSAGE: '💬',
  SUCCESS: '✅',
  ERROR: '⚠️',
  WARNING: '⚠️',
  INFO: 'ℹ️',
  SETTINGS: '⚙️',
  LOCK: '🔒',
  UNLOCK: '🔓',
  MUSIC: '🎵',
  GAME: '🎮',
  GIFT: '🎁',
  BIRTHDAY: '🎂',
  LOVE: '❤️',
  SHOP: '🛒',
  INVENTORY: '🎒',
  SHIELD: '🛡️',
  TIME: '⏳',
  TADA: '🎉',
  PIN: '📌',
  BOT: '🤖',
} as const;

export const RARITY = {
  COMMON: { name: 'Yaygın', color: 0x95A5A6, emoji: '⚪' },
  RARE: { name: 'Nadir', color: 0x3498DB, emoji: '🔵' },
  EPIC: { name: 'Epik', color: 0x9B59B6, emoji: '🟣' },
  LEGENDARY: { name: 'Efsanevi', color: 0xF1C40F, emoji: '🟡' },
  MYTHIC: { name: 'Mitolojik', color: 0xE74C3C, emoji: '🔴' },
} as const;

export const DEFAULT_ACHIEVEMENTS = [
  {
    code: 'FIRST_STEP',
    name: 'İlk Adım',
    description: 'Sunucuya katıldın ve Priv dünyasına adım attın.',
    icon: '🌱',
    rarity: 'COMMON',
    requirement: 'Katılım',
    rewardCoins: 100,
    rewardXp: 50,
  },
  {
    code: 'CHATTERBOX',
    name: 'Geveze',
    description: 'Sunucu kanallarında toplam 100 mesaj gönderdin.',
    icon: '💬',
    rarity: 'RARE',
    requirement: '100 Mesaj',
    rewardCoins: 500,
    rewardXp: 200,
  },
  {
    code: 'MESSAGE_MASTER',
    name: '1000 Mesaj',
    description: 'Sunucuda 1000 mesaja ulaştın, gerçek bir tayfa üyesisin.',
    icon: '📜',
    rarity: 'EPIC',
    requirement: '1000 Mesaj',
    rewardCoins: 2500,
    rewardXp: 1000,
  },
  {
    code: 'NIGHT_OWL',
    name: 'Gece Kuşu',
    description: 'Gece 02:00 ile 05:00 arasında aktif olarak sohbete katıldın.',
    icon: '🦉',
    rarity: 'RARE',
    requirement: 'Gece Aktifliği',
    rewardCoins: 300,
    rewardXp: 150,
  },
  {
    code: 'VOICE_BEAST',
    name: 'Voice Canavarı',
    description: 'Ses kanallarında toplam 10 saat geçirdin.',
    icon: '🎤',
    rarity: 'RARE',
    requirement: '10 Saat Ses',
    rewardCoins: 1000,
    rewardXp: 500,
  },
  {
    code: 'VOICE_LEGEND',
    name: '100 Saat Voice',
    description: 'Ses kanallarında toplam 100 saat geçirdin, oda senin evin!',
    icon: '👑',
    rarity: 'LEGENDARY',
    requirement: '100 Saat Ses',
    rewardCoins: 10000,
    rewardXp: 5000,
  },
  {
    code: 'STREAK_WARRIOR',
    name: 'Ateşli Tayfa',
    description: '7 günlük kesintisiz streak serisine ulaştın.',
    icon: '🔥',
    rarity: 'EPIC',
    requirement: '7 Günlük Streak',
    rewardCoins: 1500,
    rewardXp: 700,
  },
  {
    code: 'LUCKY_ONE',
    name: 'Şanslı',
    description: 'Mini oyunlarda üst üste 3 kez galip geldin.',
    icon: '🎲',
    rarity: 'EPIC',
    requirement: '3 Oyun Galibiyeti',
    rewardCoins: 750,
    rewardXp: 300,
  },
  {
    code: 'OG_MEMBER',
    name: 'OG',
    description: 'Sunucuda 30 günden uzun süredir bulunuyorsun.',
    icon: '💎',
    rarity: 'LEGENDARY',
    requirement: '30 Günlük Kıdem',
    rewardCoins: 5000,
    rewardXp: 2500,
  },
];

export const DEFAULT_LEVEL_ROLES = [
  { level: 5, name: 'Yeni Üye', rewardCoins: 250 },
  { level: 10, name: 'Ortamcı', rewardCoins: 1000 },
  { level: 20, name: 'Tayfa', rewardCoins: 2500 },
  { level: 30, name: 'OG', rewardCoins: 5000 },
  { level: 50, name: 'Efsane', rewardCoins: 15000 },
];

export const STREAK_MILESTONES = [
  { days: 7, rewardCoins: 500, rewardXp: 200, title: 'Haftalık Müdavim' },
  { days: 14, rewardCoins: 1200, rewardXp: 500, title: 'İki Haftalık Ateş' },
  { days: 30, rewardCoins: 3000, rewardXp: 1500, title: 'Aylık Efsane' },
  { days: 60, rewardCoins: 7500, rewardXp: 3500, title: 'Sunucu Demirbaşı' },
  { days: 100, rewardCoins: 20000, rewardXp: 10000, title: 'Yüzyılın Priv Dostu' },
];
